#!/usr/bin/env ruby
# HTTP test server for integration tests

root = File.expand_path('../..', __FILE__)
require File.join(root, %w[spec support test_server.rb])

PatronTestServer.start($stderr).join
