name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.4, 2.5, 2.6, 2.7, '3.0', 3.1]

    name: Specs - Ruby ${{ matrix.ruby-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Install libcurl
      run: |
        sudo apt-get update
        sudo apt-get -y install libcurl4 libcurl4-openssl-dev 
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run tests
      run: bundle exec rake
